// GENERATED FILE - DO NOT EDIT.
// Generated by gen_builtin_symbols.py using data from builtin_variables.json and
// builtin_function_declarations.txt.
//
// Copyright 2019 The ANGLE Project Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.
//
// SymbolTable_autogen.h:
//   Autogenerated member variables of TSymbolTable.

#ifndef COMPILER_TRANSLATOR_SYMBOLTABLE_AUTOGEN_H_
#define COMPILER_TRANSLATOR_SYMBOLTABLE_AUTOGEN_H_

namespace sh
{

class TSymbolTableBase
{
  public:
    TSymbolTableBase()                            = default;
    TSymbol *mgl_DepthRangeParameters             = nullptr;
    TSymbol *mgl_DepthRange                       = nullptr;
    TSymbol *mgl_MaxVertexAttribs                 = nullptr;
    TSymbol *mgl_MaxVertexUniformVectors          = nullptr;
    TSymbol *mgl_MaxVertexTextureImageUnits       = nullptr;
    TSymbol *mgl_MaxCombinedTextureImageUnits     = nullptr;
    TSymbol *mgl_MaxTextureImageUnits             = nullptr;
    TSymbol *mgl_MaxFragmentUniformVectors        = nullptr;
    TSymbol *mgl_MaxVaryingVectors                = nullptr;
    TSymbol *mgl_MaxDrawBuffers                   = nullptr;
    TSymbol *mgl_MaxDualSourceDrawBuffersEXT      = nullptr;
    TSymbol *mgl_MaxVertexOutputVectors           = nullptr;
    TSymbol *mgl_MaxFragmentInputVectors          = nullptr;
    TSymbol *mgl_MinProgramTexelOffset            = nullptr;
    TSymbol *mgl_MaxProgramTexelOffset            = nullptr;
    TSymbol *mgl_MaxImageUnits                    = nullptr;
    TSymbol *mgl_MaxVertexImageUniforms           = nullptr;
    TSymbol *mgl_MaxFragmentImageUniforms         = nullptr;
    TSymbol *mgl_MaxComputeImageUniforms          = nullptr;
    TSymbol *mgl_MaxCombinedImageUniforms         = nullptr;
    TSymbol *mgl_MaxCombinedShaderOutputResources = nullptr;
    TSymbol *mgl_MaxComputeWorkGroupCount         = nullptr;
    TSymbol *mgl_MaxComputeWorkGroupSize          = nullptr;
    TSymbol *mgl_MaxComputeUniformComponents      = nullptr;
    TSymbol *mgl_MaxComputeTextureImageUnits      = nullptr;
    TSymbol *mgl_MaxComputeAtomicCounters         = nullptr;
    TSymbol *mgl_MaxComputeAtomicCounterBuffers   = nullptr;
    TSymbol *mgl_MaxVertexAtomicCounters          = nullptr;
    TSymbol *mgl_MaxFragmentAtomicCounters        = nullptr;
    TSymbol *mgl_MaxCombinedAtomicCounters        = nullptr;
    TSymbol *mgl_MaxAtomicCounterBindings         = nullptr;
    TSymbol *mgl_MaxVertexAtomicCounterBuffers    = nullptr;
    TSymbol *mgl_MaxFragmentAtomicCounterBuffers  = nullptr;
    TSymbol *mgl_MaxCombinedAtomicCounterBuffers  = nullptr;
    TSymbol *mgl_MaxAtomicCounterBufferSize       = nullptr;
    TSymbol *mgl_MaxGeometryInputComponents       = nullptr;
    TSymbol *mgl_MaxGeometryOutputComponents      = nullptr;
    TSymbol *mgl_MaxGeometryImageUniforms         = nullptr;
    TSymbol *mgl_MaxGeometryTextureImageUnits     = nullptr;
    TSymbol *mgl_MaxGeometryOutputVertices        = nullptr;
    TSymbol *mgl_MaxGeometryTotalOutputComponents = nullptr;
    TSymbol *mgl_MaxGeometryUniformComponents     = nullptr;
    TSymbol *mgl_MaxGeometryAtomicCounters        = nullptr;
    TSymbol *mgl_MaxGeometryAtomicCounterBuffers  = nullptr;
    TSymbol *mgl_FragData                         = nullptr;
    TSymbol *mgl_SecondaryFragDataEXT             = nullptr;
    TSymbol *mgl_FragDepthEXT                     = nullptr;
    TSymbol *mgl_LastFragData                     = nullptr;
    TSymbol *mgl_LastFragDataNV                   = nullptr;
    TSymbol *mgl_PerVertex                        = nullptr;
    TSymbol *mgl_in                               = nullptr;
    TSymbol *mgl_PositionGS                       = nullptr;
};

}  // namespace sh

#endif  // COMPILER_TRANSLATOR_SYMBOLTABLE_AUTOGEN_H_
