#!/usr/bin/python3
# Copyright 2023 The ANGLE Project Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

import os
import subprocess
import sys
import argparse

template_header_boilerplate = """// GENERATED FILE - DO NOT EDIT.
// Generated by {script_name}
//
// Copyright 2020 The ANGLE Project Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.
//
"""


def embed_in_header(source_file, ext_source_file, variable_name_prefix, dest_header_file):
    boilerplate_code = template_header_boilerplate.format(
        script_name=os.path.basename(sys.argv[0]))

    with open(source_file, 'rb') as f:
        source_data = f.read()

    # new metal lib generated by newer metal compiler.
    with open(ext_source_file, 'rb') as f:
        ext_source_data = f.read()

    with open(dest_header_file, 'wt') as out_file:
        out_file.write(boilerplate_code)
        out_file.write('\n')
        out_file.write('// C++ string version of default shaders mtllib.\n\n')
        out_file.write('\n\nstatic constexpr uint8_t ' + variable_name_prefix + '[] = {\n')
        for byte in source_data:
            out_file.write(f"{byte}, ")
        out_file.write('\n')
        out_file.write('};\n')
        out_file.write('\n')
        out_file.write(
            '// C++ string version of default shaders mtllib (for newer metal version).\n\n')
        out_file.write('\n\nstatic constexpr uint8_t ' + variable_name_prefix + 'Extended[] = {\n')
        for byte in ext_source_data:
            out_file.write(f"{byte}, ")
        out_file.write('\n')
        out_file.write('};\n')
        out_file.close()


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument('--source')
    parser.add_argument('--ext-source')
    parser.add_argument('--variable-name-prefix')
    parser.add_argument('--header')
    args = parser.parse_args()

    embed_in_header(args.source, args.ext_source, args.variable_name_prefix, args.header)


if __name__ == '__main__':
    sys.exit(main())
