// GENERATED FILE - DO NOT EDIT.
// Generated by gen_packed_enums.py using data from packed_egl_enums.json.
//
// Copyright 2018 The ANGLE Project Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.
//
// PackedEGLEnums_autogen.cpp:
//   Implements ANGLE-specific enums classes for EGLenums and functions operating
//   on them.

#include "libANGLE/PackedEGLEnums_autogen.h"
#include "common/debug.h"

namespace egl
{

}  // namespace egl
