#!/usr/bin/python
# Copyright 2018 The ANGLE Project Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.
#
# gen_vk_internal_shaders.py:
#  Code generation for internal Vulkan shaders. Should be run when an intenal
#  shader program is changed, added or removed.

from datetime import date
import os
import subprocess
import sys

out_file_cpp = 'vk_internal_shaders_autogen.cpp'
out_file_h = 'vk_internal_shaders_autogen.h'
out_file_gni = 'vk_internal_shaders_autogen.gni'

def get_var_name(shader):
    return "k" + os.path.basename(shader).replace(".", "_")

def get_shader_id(shader):
    file = os.path.splitext(os.path.basename(shader))[0]
    return file.replace(".", "_")

def get_output_name(shader):
    return os.path.join('shaders', 'gen', os.path.basename(shader) + ".inc")

shaders_dir = os.path.join('shaders', 'src')
if not os.path.isdir(shaders_dir):
    raise Exception("Could not find shaders directory")

input_shaders = sorted([os.path.join(shaders_dir, shader) for shader in os.listdir(shaders_dir)])
output_shaders = sorted([get_output_name(shader) for shader in input_shaders])

outputs = output_shaders + [out_file_cpp, out_file_h]

# Handle inputs/outputs for run_code_generation.py's auto_script
if len(sys.argv) == 2 and sys.argv[1] == 'inputs':
    print(",".join(input_shaders))
    sys.exit(0)
elif len(sys.argv) == 2 and sys.argv[1] == 'outputs':
    print(",".join(outputs))
    sys.exit(0)

# STEP 1: Call glslang to generate the internal shaders into small .inc files.

# a) Get the path to the glslang binary from the script directory.
def find_build_path(path):
    out = os.path.join(path, "out")
    if (os.path.isdir(out)):
        for o in os.listdir(out):
            subdir = os.path.join(out, o)
            if os.path.isdir(subdir):
                argsgn = os.path.join(subdir, "args.gn")
                if os.path.isfile(argsgn):
                    return subdir
    else:
        parent = os.path.join(path, "..")
        if (os.path.isdir(parent)):
            return find_build_path(parent)
        else:
            raise Exception("Could not find GN out directory")

build_path = find_build_path(".")
print("Using glslang_validator from '" + build_path + "'")
result = subprocess.call(['ninja', '-C', build_path, 'glslang_validator'])
if result != 0:
    raise Exception("Error building glslang_validator")

glslang_binary = 'glslang_validator'
if os.name == 'nt':
    glslang_binary += '.exe'
glslang_path = os.path.join(build_path, glslang_binary)
if not os.path.isfile(glslang_path):
    raise Exception("Could not find " + glslang_binary)

# b) Iterate over the shaders and call glslang with the right arguments.
for shader_file in input_shaders:
    glslang_args = [
        glslang_path,
        '-V',                                            # Output mode is Vulkan
        '--variable-name', get_var_name(shader_file),    # C-style variable name
        '-o', get_output_name(shader_file),              # Output file
        shader_file,                                     # Input GLSL shader
    ]
    result = subprocess.call(glslang_args)
    if result != 0:
        raise Exception("Error compiling " + shader_file)

# STEP 2: Consolidate the .inc files into an auto-generated cpp/h library.
template_shader_library_cpp = """// GENERATED FILE - DO NOT EDIT.
// Generated by {script_name} using data from {input_file_name}
//
// Copyright {copyright_year} The ANGLE Project Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.
//
// {out_file_name}:
//   Pre-generated shader library for the ANGLE Vulkan back-end.

#include "libANGLE/renderer/vulkan/vk_internal_shaders_autogen.h"

#include "common/debug.h"

namespace rx
{{
namespace vk
{{
namespace
{{
{internal_shader_includes}
}}  // anonymous namespace

const uint32_t *GetInternalShaderCode(InternalShaderID shaderID)
{{
    switch (shaderID)
    {{
{internal_shader_code_cases}
        default:
            UNREACHABLE();
            return nullptr;
    }}
}}

size_t GetInternalShaderCodeSize(InternalShaderID shaderID)
{{
    switch (shaderID)
    {{
{internal_shader_code_size_cases}
        default:
            UNREACHABLE();
            return 0;
    }}
}}
}}  // namespace vk
}}  // namespace rx
"""

template_shader_library_h = """// GENERATED FILE - DO NOT EDIT.
// Generated by {script_name} using data from {input_file_name}
//
// Copyright {copyright_year} The ANGLE Project Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.
//
// {out_file_name}:
//   Pre-generated shader library for the ANGLE Vulkan back-end.

#ifndef LIBANGLE_RENDERER_VULKAN_VK_INTERNAL_SHADERS_AUTOGEN_H_
#define LIBANGLE_RENDERER_VULKAN_VK_INTERNAL_SHADERS_AUTOGEN_H_

#include <stdint.h>

namespace rx
{{
namespace vk
{{
enum class InternalShaderID
{{
{internal_shader_ids}
}};

const uint32_t *GetInternalShaderCode(InternalShaderID shaderID);
size_t GetInternalShaderCodeSize(InternalShaderID shaderID);
}}  // namespace vk
}}  // namespace rx

#endif  // LIBANGLE_RENDERER_VULKAN_VK_INTERNAL_SHADERS_AUTOGEN_H_
"""

template_internal_shader_case = """{i}{i}case InternalShaderID::{id}:
{i}{i}{i}return {var};
"""

# STEP 3: Create a gni file with the generated files.
template_shader_includes_gni = """# GENERATED FILE - DO NOT EDIT.
# Generated by {script_name} using data from {input_file_name}
#
# Copyright {copyright_year} The ANGLE Project Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.
#
# {out_file_name}:
#   List of generated shaders for inclusion in ANGLE's build process.

angle_vulkan_internal_shaders = [
{shaders_list}
]
"""

def gen_shader_code_case(shader):
    name = os.path.basename(shader)
    return template_internal_shader_case.format(
        i = "    ",
        id = get_shader_id(name),
        var = get_var_name(name)[0:-4])

def gen_shader_size_case(shader):
    name = os.path.basename(shader)
    return template_internal_shader_case.format(
        i = "    ",
        id = get_shader_id(name),
        var = "sizeof(%s)" % get_var_name(name)[0:-4])

def slash(s):
    return s.replace('\\', '/')

def gen_shader_include(shader):
    return '#include "libANGLE/renderer/vulkan/%s"' % slash(shader)

with open(out_file_cpp, 'w') as outfile:
    includes = "\n".join([gen_shader_include(shader) for shader in output_shaders])
    code_cases = "\n".join([gen_shader_code_case(shader) for shader in output_shaders])
    size_cases = "\n".join([gen_shader_size_case(shader) for shader in output_shaders])
    outcode = template_shader_library_cpp.format(
        script_name = __file__,
        copyright_year = date.today().year,
        out_file_name = out_file_cpp,
        input_file_name = 'shaders/src/*',
        internal_shader_includes = includes,
        internal_shader_code_cases = code_cases,
        internal_shader_code_size_cases = size_cases)
    outfile.write(outcode)
    outfile.close()

with open(out_file_h, 'w') as outfile:
    ids = ",\n".join([get_shader_id(shader) for shader in output_shaders] + ["EnumCount"])
    outcode = template_shader_library_h.format(
        script_name = __file__,
        copyright_year = date.today().year,
        out_file_name = out_file_h,
        input_file_name = 'shaders/src/*',
        internal_shader_ids = ids)
    outfile.write(outcode)
    outfile.close()

with open(out_file_gni, 'w') as outfile:
    outcode = template_shader_includes_gni.format(
        script_name = __file__,
        copyright_year = date.today().year,
        out_file_name = out_file_gni,
        input_file_name = 'shaders/src/*',
        shaders_list = ',\n'.join(['  "' + slash(shader) + '"' for shader in output_shaders]))
    outfile.write(outcode)
    outfile.close()
