// GENERATED FILE - DO NOT EDIT.
// Generated by generate_entry_points.py using data from gl.xml.
//
// Copyright 2022 The ANGLE Project Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.
//
// layer_entry_points_gles_1_0_autogen.cpp:
//   Layer functions for the OpenGL ES 1.0 entry points.

#include "libGLESv2/layer_entry_points_gles_1_0_autogen.h"
#include "common/entry_points_enum_autogen.h"
#include "labelLayer.h"
#include "libANGLE/capture/gl_enum_utils.h"

using namespace gl;

namespace agi_layer
{

void GL_APIENTRY GL_AlphaFunc(GLenum func, GLfloat ref)
{
    char entryPointMessage[512];
    std::sprintf(entryPointMessage, "glAlphaFunc(func = %s, ref = %f)",
                 GLenumToString(GLESEnum::AlphaFunction, func), ref);
    g_debug_message_insert(GL_DEBUG_SOURCE_THIRD_PARTY_KHR, GL_DEBUG_TYPE_OTHER_KHR,
                           static_cast<GLuint>(angle::EntryPoint::GLAlphaFunc),
                           GL_DEBUG_SEVERITY_NOTIFICATION_KHR, -1, entryPointMessage);

    // Call down to the next layer
    void *entry             = funcMap["glAlphaFunc"];
    PFNGLALPHAFUNCPROC next = reinterpret_cast<PFNGLALPHAFUNCPROC>(entry);
    next(func, ref);
}

void GL_APIENTRY GL_AlphaFuncx(GLenum func, GLfixed ref)
{
    char entryPointMessage[512];
    std::sprintf(entryPointMessage, "glAlphaFuncx(func = %s, ref = 0x%X)",
                 GLenumToString(GLESEnum::AlphaFunction, func), ref);
    g_debug_message_insert(GL_DEBUG_SOURCE_THIRD_PARTY_KHR, GL_DEBUG_TYPE_OTHER_KHR,
                           static_cast<GLuint>(angle::EntryPoint::GLAlphaFuncx),
                           GL_DEBUG_SEVERITY_NOTIFICATION_KHR, -1, entryPointMessage);

    // Call down to the next layer
    void *entry              = funcMap["glAlphaFuncx"];
    PFNGLALPHAFUNCXPROC next = reinterpret_cast<PFNGLALPHAFUNCXPROC>(entry);
    next(func, ref);
}

void GL_APIENTRY GL_ClearColorx(GLfixed red, GLfixed green, GLfixed blue, GLfixed alpha)
{
    char entryPointMessage[512];
    std::sprintf(entryPointMessage,
                 "glClearColorx(red = 0x%X, green = 0x%X, blue = 0x%X, alpha = 0x%X)", red, green,
                 blue, alpha);
    g_debug_message_insert(GL_DEBUG_SOURCE_THIRD_PARTY_KHR, GL_DEBUG_TYPE_OTHER_KHR,
                           static_cast<GLuint>(angle::EntryPoint::GLClearColorx),
                           GL_DEBUG_SEVERITY_NOTIFICATION_KHR, -1, entryPointMessage);

    // Call down to the next layer
    void *entry               = funcMap["glClearColorx"];
    PFNGLCLEARCOLORXPROC next = reinterpret_cast<PFNGLCLEARCOLORXPROC>(entry);
    next(red, green, blue, alpha);
}

void GL_APIENTRY GL_ClearDepthx(GLfixed depth)
{
    char entryPointMessage[512];
    std::sprintf(entryPointMessage, "glClearDepthx(depth = 0x%X)", depth);
    g_debug_message_insert(GL_DEBUG_SOURCE_THIRD_PARTY_KHR, GL_DEBUG_TYPE_OTHER_KHR,
                           static_cast<GLuint>(angle::EntryPoint::GLClearDepthx),
                           GL_DEBUG_SEVERITY_NOTIFICATION_KHR, -1, entryPointMessage);

    // Call down to the next layer
    void *entry               = funcMap["glClearDepthx"];
    PFNGLCLEARDEPTHXPROC next = reinterpret_cast<PFNGLCLEARDEPTHXPROC>(entry);
    next(depth);
}

void GL_APIENTRY GL_ClientActiveTexture(GLenum texture)
{
    char entryPointMessage[512];
    std::sprintf(entryPointMessage, "glClientActiveTexture(texture = %s)",
                 GLenumToString(GLESEnum::TextureUnit, texture));
    g_debug_message_insert(GL_DEBUG_SOURCE_THIRD_PARTY_KHR, GL_DEBUG_TYPE_OTHER_KHR,
                           static_cast<GLuint>(angle::EntryPoint::GLClientActiveTexture),
                           GL_DEBUG_SEVERITY_NOTIFICATION_KHR, -1, entryPointMessage);

    // Call down to the next layer
    void *entry                       = funcMap["glClientActiveTexture"];
    PFNGLCLIENTACTIVETEXTUREPROC next = reinterpret_cast<PFNGLCLIENTACTIVETEXTUREPROC>(entry);
    next(texture);
}

void GL_APIENTRY GL_ClipPlanef(GLenum p, const GLfloat *eqn)
{
    char entryPointMessage[512];
    std::sprintf(entryPointMessage, "glClipPlanef(p = %s, eqn = 0x%016" PRIxPTR ")",
                 GLenumToString(GLESEnum::ClipPlaneName, p), (uintptr_t)eqn);
    g_debug_message_insert(GL_DEBUG_SOURCE_THIRD_PARTY_KHR, GL_DEBUG_TYPE_OTHER_KHR,
                           static_cast<GLuint>(angle::EntryPoint::GLClipPlanef),
                           GL_DEBUG_SEVERITY_NOTIFICATION_KHR, -1, entryPointMessage);

    // Call down to the next layer
    void *entry              = funcMap["glClipPlanef"];
    PFNGLCLIPPLANEFPROC next = reinterpret_cast<PFNGLCLIPPLANEFPROC>(entry);
    next(p, eqn);
}

void GL_APIENTRY GL_ClipPlanex(GLenum plane, const GLfixed *equation)
{
    char entryPointMessage[512];
    std::sprintf(entryPointMessage, "glClipPlanex(plane = %s, equation = 0x%016" PRIxPTR ")",
                 GLenumToString(GLESEnum::ClipPlaneName, plane), (uintptr_t)equation);
    g_debug_message_insert(GL_DEBUG_SOURCE_THIRD_PARTY_KHR, GL_DEBUG_TYPE_OTHER_KHR,
                           static_cast<GLuint>(angle::EntryPoint::GLClipPlanex),
                           GL_DEBUG_SEVERITY_NOTIFICATION_KHR, -1, entryPointMessage);

    // Call down to the next layer
    void *entry              = funcMap["glClipPlanex"];
    PFNGLCLIPPLANEXPROC next = reinterpret_cast<PFNGLCLIPPLANEXPROC>(entry);
    next(plane, equation);
}

void GL_APIENTRY GL_Color4f(GLfloat red, GLfloat green, GLfloat blue, GLfloat alpha)
{
    char entryPointMessage[512];
    std::sprintf(entryPointMessage, "glColor4f(red = %f, green = %f, blue = %f, alpha = %f)", red,
                 green, blue, alpha);
    g_debug_message_insert(GL_DEBUG_SOURCE_THIRD_PARTY_KHR, GL_DEBUG_TYPE_OTHER_KHR,
                           static_cast<GLuint>(angle::EntryPoint::GLColor4f),
                           GL_DEBUG_SEVERITY_NOTIFICATION_KHR, -1, entryPointMessage);

    // Call down to the next layer
    void *entry           = funcMap["glColor4f"];
    PFNGLCOLOR4FPROC next = reinterpret_cast<PFNGLCOLOR4FPROC>(entry);
    next(red, green, blue, alpha);
}

void GL_APIENTRY GL_Color4ub(GLubyte red, GLubyte green, GLubyte blue, GLubyte alpha)
{
    char entryPointMessage[512];
    std::sprintf(entryPointMessage, "glColor4ub(red = %d, green = %d, blue = %d, alpha = %d)", red,
                 green, blue, alpha);
    g_debug_message_insert(GL_DEBUG_SOURCE_THIRD_PARTY_KHR, GL_DEBUG_TYPE_OTHER_KHR,
                           static_cast<GLuint>(angle::EntryPoint::GLColor4ub),
                           GL_DEBUG_SEVERITY_NOTIFICATION_KHR, -1, entryPointMessage);

    // Call down to the next layer
    void *entry            = funcMap["glColor4ub"];
    PFNGLCOLOR4UBPROC next = reinterpret_cast<PFNGLCOLOR4UBPROC>(entry);
    next(red, green, blue, alpha);
}

void GL_APIENTRY GL_Color4x(GLfixed red, GLfixed green, GLfixed blue, GLfixed alpha)
{
    char entryPointMessage[512];
    std::sprintf(entryPointMessage,
                 "glColor4x(red = 0x%X, green = 0x%X, blue = 0x%X, alpha = 0x%X)", red, green, blue,
                 alpha);
    g_debug_message_insert(GL_DEBUG_SOURCE_THIRD_PARTY_KHR, GL_DEBUG_TYPE_OTHER_KHR,
                           static_cast<GLuint>(angle::EntryPoint::GLColor4x),
                           GL_DEBUG_SEVERITY_NOTIFICATION_KHR, -1, entryPointMessage);

    // Call down to the next layer
    void *entry           = funcMap["glColor4x"];
    PFNGLCOLOR4XPROC next = reinterpret_cast<PFNGLCOLOR4XPROC>(entry);
    next(red, green, blue, alpha);
}

void GL_APIENTRY GL_ColorPointer(GLint size, GLenum type, GLsizei stride, const void *pointer)
{
    char entryPointMessage[512];
    std::sprintf(entryPointMessage,
                 "glColorPointer(size = %d, type = %s, stride = %d, pointer = 0x%016" PRIxPTR ")",
                 size, GLenumToString(GLESEnum::ColorPointerType, type), stride,
                 (uintptr_t)pointer);
    g_debug_message_insert(GL_DEBUG_SOURCE_THIRD_PARTY_KHR, GL_DEBUG_TYPE_OTHER_KHR,
                           static_cast<GLuint>(angle::EntryPoint::GLColorPointer),
                           GL_DEBUG_SEVERITY_NOTIFICATION_KHR, -1, entryPointMessage);

    // Call down to the next layer
    void *entry                = funcMap["glColorPointer"];
    PFNGLCOLORPOINTERPROC next = reinterpret_cast<PFNGLCOLORPOINTERPROC>(entry);
    next(size, type, stride, pointer);
}

void GL_APIENTRY GL_DepthRangex(GLfixed n, GLfixed f)
{
    char entryPointMessage[512];
    std::sprintf(entryPointMessage, "glDepthRangex(n = 0x%X, f = 0x%X)", n, f);
    g_debug_message_insert(GL_DEBUG_SOURCE_THIRD_PARTY_KHR, GL_DEBUG_TYPE_OTHER_KHR,
                           static_cast<GLuint>(angle::EntryPoint::GLDepthRangex),
                           GL_DEBUG_SEVERITY_NOTIFICATION_KHR, -1, entryPointMessage);

    // Call down to the next layer
    void *entry               = funcMap["glDepthRangex"];
    PFNGLDEPTHRANGEXPROC next = reinterpret_cast<PFNGLDEPTHRANGEXPROC>(entry);
    next(n, f);
}

void GL_APIENTRY GL_DisableClientState(GLenum array)
{
    char entryPointMessage[512];
    std::sprintf(entryPointMessage, "glDisableClientState(array = %s)",
                 GLenumToString(GLESEnum::EnableCap, array));
    g_debug_message_insert(GL_DEBUG_SOURCE_THIRD_PARTY_KHR, GL_DEBUG_TYPE_OTHER_KHR,
                           static_cast<GLuint>(angle::EntryPoint::GLDisableClientState),
                           GL_DEBUG_SEVERITY_NOTIFICATION_KHR, -1, entryPointMessage);

    // Call down to the next layer
    void *entry                      = funcMap["glDisableClientState"];
    PFNGLDISABLECLIENTSTATEPROC next = reinterpret_cast<PFNGLDISABLECLIENTSTATEPROC>(entry);
    next(array);
}

void GL_APIENTRY GL_EnableClientState(GLenum array)
{
    char entryPointMessage[512];
    std::sprintf(entryPointMessage, "glEnableClientState(array = %s)",
                 GLenumToString(GLESEnum::EnableCap, array));
    g_debug_message_insert(GL_DEBUG_SOURCE_THIRD_PARTY_KHR, GL_DEBUG_TYPE_OTHER_KHR,
                           static_cast<GLuint>(angle::EntryPoint::GLEnableClientState),
                           GL_DEBUG_SEVERITY_NOTIFICATION_KHR, -1, entryPointMessage);

    // Call down to the next layer
    void *entry                     = funcMap["glEnableClientState"];
    PFNGLENABLECLIENTSTATEPROC next = reinterpret_cast<PFNGLENABLECLIENTSTATEPROC>(entry);
    next(array);
}

void GL_APIENTRY GL_Fogf(GLenum pname, GLfloat param)
{
    char entryPointMessage[512];
    std::sprintf(entryPointMessage, "glFogf(pname = %s, param = %f)",
                 GLenumToString(GLESEnum::FogParameter, pname), param);
    g_debug_message_insert(GL_DEBUG_SOURCE_THIRD_PARTY_KHR, GL_DEBUG_TYPE_OTHER_KHR,
                           static_cast<GLuint>(angle::EntryPoint::GLFogf),
                           GL_DEBUG_SEVERITY_NOTIFICATION_KHR, -1, entryPointMessage);

    // Call down to the next layer
    void *entry        = funcMap["glFogf"];
    PFNGLFOGFPROC next = reinterpret_cast<PFNGLFOGFPROC>(entry);
    next(pname, param);
}

void GL_APIENTRY GL_Fogfv(GLenum pname, const GLfloat *params)
{
    char entryPointMessage[512];
    std::sprintf(entryPointMessage, "glFogfv(pname = %s, params = 0x%016" PRIxPTR ")",
                 GLenumToString(GLESEnum::FogParameter, pname), (uintptr_t)params);
    g_debug_message_insert(GL_DEBUG_SOURCE_THIRD_PARTY_KHR, GL_DEBUG_TYPE_OTHER_KHR,
                           static_cast<GLuint>(angle::EntryPoint::GLFogfv),
                           GL_DEBUG_SEVERITY_NOTIFICATION_KHR, -1, entryPointMessage);

    // Call down to the next layer
    void *entry         = funcMap["glFogfv"];
    PFNGLFOGFVPROC next = reinterpret_cast<PFNGLFOGFVPROC>(entry);
    next(pname, params);
}

void GL_APIENTRY GL_Fogx(GLenum pname, GLfixed param)
{
    char entryPointMessage[512];
    std::sprintf(entryPointMessage, "glFogx(pname = %s, param = 0x%X)",
                 GLenumToString(GLESEnum::FogPName, pname), param);
    g_debug_message_insert(GL_DEBUG_SOURCE_THIRD_PARTY_KHR, GL_DEBUG_TYPE_OTHER_KHR,
                           static_cast<GLuint>(angle::EntryPoint::GLFogx),
                           GL_DEBUG_SEVERITY_NOTIFICATION_KHR, -1, entryPointMessage);

    // Call down to the next layer
    void *entry        = funcMap["glFogx"];
    PFNGLFOGXPROC next = reinterpret_cast<PFNGLFOGXPROC>(entry);
    next(pname, param);
}

void GL_APIENTRY GL_Fogxv(GLenum pname, const GLfixed *param)
{
    char entryPointMessage[512];
    std::sprintf(entryPointMessage, "glFogxv(pname = %s, param = 0x%016" PRIxPTR ")",
                 GLenumToString(GLESEnum::FogPName, pname), (uintptr_t)param);
    g_debug_message_insert(GL_DEBUG_SOURCE_THIRD_PARTY_KHR, GL_DEBUG_TYPE_OTHER_KHR,
                           static_cast<GLuint>(angle::EntryPoint::GLFogxv),
                           GL_DEBUG_SEVERITY_NOTIFICATION_KHR, -1, entryPointMessage);

    // Call down to the next layer
    void *entry         = funcMap["glFogxv"];
    PFNGLFOGXVPROC next = reinterpret_cast<PFNGLFOGXVPROC>(entry);
    next(pname, param);
}

void GL_APIENTRY GL_Frustumf(GLfloat l, GLfloat r, GLfloat b, GLfloat t, GLfloat n, GLfloat f)
{
    char entryPointMessage[512];
    std::sprintf(entryPointMessage, "glFrustumf(l = %f, r = %f, b = %f, t = %f, n = %f, f = %f)", l,
                 r, b, t, n, f);
    g_debug_message_insert(GL_DEBUG_SOURCE_THIRD_PARTY_KHR, GL_DEBUG_TYPE_OTHER_KHR,
                           static_cast<GLuint>(angle::EntryPoint::GLFrustumf),
                           GL_DEBUG_SEVERITY_NOTIFICATION_KHR, -1, entryPointMessage);

    // Call down to the next layer
    void *entry            = funcMap["glFrustumf"];
    PFNGLFRUSTUMFPROC next = reinterpret_cast<PFNGLFRUSTUMFPROC>(entry);
    next(l, r, b, t, n, f);
}

void GL_APIENTRY GL_Frustumx(GLfixed l, GLfixed r, GLfixed b, GLfixed t, GLfixed n, GLfixed f)
{
    char entryPointMessage[512];
    std::sprintf(entryPointMessage,
                 "glFrustumx(l = 0x%X, r = 0x%X, b = 0x%X, t = 0x%X, n = 0x%X, f = 0x%X)", l, r, b,
                 t, n, f);
    g_debug_message_insert(GL_DEBUG_SOURCE_THIRD_PARTY_KHR, GL_DEBUG_TYPE_OTHER_KHR,
                           static_cast<GLuint>(angle::EntryPoint::GLFrustumx),
                           GL_DEBUG_SEVERITY_NOTIFICATION_KHR, -1, entryPointMessage);

    // Call down to the next layer
    void *entry            = funcMap["glFrustumx"];
    PFNGLFRUSTUMXPROC next = reinterpret_cast<PFNGLFRUSTUMXPROC>(entry);
    next(l, r, b, t, n, f);
}

void GL_APIENTRY GL_GetClipPlanef(GLenum plane, GLfloat *equation)
{
    char entryPointMessage[512];
    std::sprintf(entryPointMessage, "glGetClipPlanef(plane = %s, equation = 0x%016" PRIxPTR ")",
                 GLenumToString(GLESEnum::ClipPlaneName, plane), (uintptr_t)equation);
    g_debug_message_insert(GL_DEBUG_SOURCE_THIRD_PARTY_KHR, GL_DEBUG_TYPE_OTHER_KHR,
                           static_cast<GLuint>(angle::EntryPoint::GLGetClipPlanef),
                           GL_DEBUG_SEVERITY_NOTIFICATION_KHR, -1, entryPointMessage);

    // Call down to the next layer
    void *entry                 = funcMap["glGetClipPlanef"];
    PFNGLGETCLIPPLANEFPROC next = reinterpret_cast<PFNGLGETCLIPPLANEFPROC>(entry);
    next(plane, equation);
}

void GL_APIENTRY GL_GetClipPlanex(GLenum plane, GLfixed *equation)
{
    char entryPointMessage[512];
    std::sprintf(entryPointMessage, "glGetClipPlanex(plane = %s, equation = 0x%016" PRIxPTR ")",
                 GLenumToString(GLESEnum::ClipPlaneName, plane), (uintptr_t)equation);
    g_debug_message_insert(GL_DEBUG_SOURCE_THIRD_PARTY_KHR, GL_DEBUG_TYPE_OTHER_KHR,
                           static_cast<GLuint>(angle::EntryPoint::GLGetClipPlanex),
                           GL_DEBUG_SEVERITY_NOTIFICATION_KHR, -1, entryPointMessage);

    // Call down to the next layer
    void *entry                 = funcMap["glGetClipPlanex"];
    PFNGLGETCLIPPLANEXPROC next = reinterpret_cast<PFNGLGETCLIPPLANEXPROC>(entry);
    next(plane, equation);
}

void GL_APIENTRY GL_GetFixedv(GLenum pname, GLfixed *params)
{
    char entryPointMessage[512];
    std::sprintf(entryPointMessage, "glGetFixedv(pname = %s, params = 0x%016" PRIxPTR ")",
                 GLenumToString(GLESEnum::GetPName, pname), (uintptr_t)params);
    g_debug_message_insert(GL_DEBUG_SOURCE_THIRD_PARTY_KHR, GL_DEBUG_TYPE_OTHER_KHR,
                           static_cast<GLuint>(angle::EntryPoint::GLGetFixedv),
                           GL_DEBUG_SEVERITY_NOTIFICATION_KHR, -1, entryPointMessage);

    // Call down to the next layer
    void *entry             = funcMap["glGetFixedv"];
    PFNGLGETFIXEDVPROC next = reinterpret_cast<PFNGLGETFIXEDVPROC>(entry);
    next(pname, params);
}

void GL_APIENTRY GL_GetLightfv(GLenum light, GLenum pname, GLfloat *params)
{
    char entryPointMessage[512];
    std::sprintf(entryPointMessage,
                 "glGetLightfv(light = %s, pname = %s, params = 0x%016" PRIxPTR ")",
                 GLenumToString(GLESEnum::LightName, light),
                 GLenumToString(GLESEnum::LightParameter, pname), (uintptr_t)params);
    g_debug_message_insert(GL_DEBUG_SOURCE_THIRD_PARTY_KHR, GL_DEBUG_TYPE_OTHER_KHR,
                           static_cast<GLuint>(angle::EntryPoint::GLGetLightfv),
                           GL_DEBUG_SEVERITY_NOTIFICATION_KHR, -1, entryPointMessage);

    // Call down to the next layer
    void *entry              = funcMap["glGetLightfv"];
    PFNGLGETLIGHTFVPROC next = reinterpret_cast<PFNGLGETLIGHTFVPROC>(entry);
    next(light, pname, params);
}

void GL_APIENTRY GL_GetLightxv(GLenum light, GLenum pname, GLfixed *params)
{
    char entryPointMessage[512];
    std::sprintf(entryPointMessage,
                 "glGetLightxv(light = %s, pname = %s, params = 0x%016" PRIxPTR ")",
                 GLenumToString(GLESEnum::LightName, light),
                 GLenumToString(GLESEnum::LightParameter, pname), (uintptr_t)params);
    g_debug_message_insert(GL_DEBUG_SOURCE_THIRD_PARTY_KHR, GL_DEBUG_TYPE_OTHER_KHR,
                           static_cast<GLuint>(angle::EntryPoint::GLGetLightxv),
                           GL_DEBUG_SEVERITY_NOTIFICATION_KHR, -1, entryPointMessage);

    // Call down to the next layer
    void *entry              = funcMap["glGetLightxv"];
    PFNGLGETLIGHTXVPROC next = reinterpret_cast<PFNGLGETLIGHTXVPROC>(entry);
    next(light, pname, params);
}

void GL_APIENTRY GL_GetMaterialfv(GLenum face, GLenum pname, GLfloat *params)
{
    char entryPointMessage[512];
    std::sprintf(entryPointMessage,
                 "glGetMaterialfv(face = %s, pname = %s, params = 0x%016" PRIxPTR ")",
                 GLenumToString(GLESEnum::MaterialFace, face),
                 GLenumToString(GLESEnum::MaterialParameter, pname), (uintptr_t)params);
    g_debug_message_insert(GL_DEBUG_SOURCE_THIRD_PARTY_KHR, GL_DEBUG_TYPE_OTHER_KHR,
                           static_cast<GLuint>(angle::EntryPoint::GLGetMaterialfv),
                           GL_DEBUG_SEVERITY_NOTIFICATION_KHR, -1, entryPointMessage);

    // Call down to the next layer
    void *entry                 = funcMap["glGetMaterialfv"];
    PFNGLGETMATERIALFVPROC next = reinterpret_cast<PFNGLGETMATERIALFVPROC>(entry);
    next(face, pname, params);
}

void GL_APIENTRY GL_GetMaterialxv(GLenum face, GLenum pname, GLfixed *params)
{
    char entryPointMessage[512];
    std::sprintf(entryPointMessage,
                 "glGetMaterialxv(face = %s, pname = %s, params = 0x%016" PRIxPTR ")",
                 GLenumToString(GLESEnum::MaterialFace, face),
                 GLenumToString(GLESEnum::MaterialParameter, pname), (uintptr_t)params);
    g_debug_message_insert(GL_DEBUG_SOURCE_THIRD_PARTY_KHR, GL_DEBUG_TYPE_OTHER_KHR,
                           static_cast<GLuint>(angle::EntryPoint::GLGetMaterialxv),
                           GL_DEBUG_SEVERITY_NOTIFICATION_KHR, -1, entryPointMessage);

    // Call down to the next layer
    void *entry                 = funcMap["glGetMaterialxv"];
    PFNGLGETMATERIALXVPROC next = reinterpret_cast<PFNGLGETMATERIALXVPROC>(entry);
    next(face, pname, params);
}

void GL_APIENTRY GL_GetTexEnvfv(GLenum target, GLenum pname, GLfloat *params)
{
    char entryPointMessage[512];
    std::sprintf(entryPointMessage,
                 "glGetTexEnvfv(target = %s, pname = %s, params = 0x%016" PRIxPTR ")",
                 GLenumToString(GLESEnum::TextureEnvTarget, target),
                 GLenumToString(GLESEnum::TextureEnvParameter, pname), (uintptr_t)params);
    g_debug_message_insert(GL_DEBUG_SOURCE_THIRD_PARTY_KHR, GL_DEBUG_TYPE_OTHER_KHR,
                           static_cast<GLuint>(angle::EntryPoint::GLGetTexEnvfv),
                           GL_DEBUG_SEVERITY_NOTIFICATION_KHR, -1, entryPointMessage);

    // Call down to the next layer
    void *entry               = funcMap["glGetTexEnvfv"];
    PFNGLGETTEXENVFVPROC next = reinterpret_cast<PFNGLGETTEXENVFVPROC>(entry);
    next(target, pname, params);
}

void GL_APIENTRY GL_GetTexEnviv(GLenum target, GLenum pname, GLint *params)
{
    char entryPointMessage[512];
    std::sprintf(entryPointMessage,
                 "glGetTexEnviv(target = %s, pname = %s, params = 0x%016" PRIxPTR ")",
                 GLenumToString(GLESEnum::TextureEnvTarget, target),
                 GLenumToString(GLESEnum::TextureEnvParameter, pname), (uintptr_t)params);
    g_debug_message_insert(GL_DEBUG_SOURCE_THIRD_PARTY_KHR, GL_DEBUG_TYPE_OTHER_KHR,
                           static_cast<GLuint>(angle::EntryPoint::GLGetTexEnviv),
                           GL_DEBUG_SEVERITY_NOTIFICATION_KHR, -1, entryPointMessage);

    // Call down to the next layer
    void *entry               = funcMap["glGetTexEnviv"];
    PFNGLGETTEXENVIVPROC next = reinterpret_cast<PFNGLGETTEXENVIVPROC>(entry);
    next(target, pname, params);
}

void GL_APIENTRY GL_GetTexEnvxv(GLenum target, GLenum pname, GLfixed *params)
{
    char entryPointMessage[512];
    std::sprintf(entryPointMessage,
                 "glGetTexEnvxv(target = %s, pname = %s, params = 0x%016" PRIxPTR ")",
                 GLenumToString(GLESEnum::TextureEnvTarget, target),
                 GLenumToString(GLESEnum::TextureEnvParameter, pname), (uintptr_t)params);
    g_debug_message_insert(GL_DEBUG_SOURCE_THIRD_PARTY_KHR, GL_DEBUG_TYPE_OTHER_KHR,
                           static_cast<GLuint>(angle::EntryPoint::GLGetTexEnvxv),
                           GL_DEBUG_SEVERITY_NOTIFICATION_KHR, -1, entryPointMessage);

    // Call down to the next layer
    void *entry               = funcMap["glGetTexEnvxv"];
    PFNGLGETTEXENVXVPROC next = reinterpret_cast<PFNGLGETTEXENVXVPROC>(entry);
    next(target, pname, params);
}

void GL_APIENTRY GL_GetTexParameterxv(GLenum target, GLenum pname, GLfixed *params)
{
    char entryPointMessage[512];
    std::sprintf(entryPointMessage,
                 "glGetTexParameterxv(target = %s, pname = %s, params = 0x%016" PRIxPTR ")",
                 GLenumToString(GLESEnum::TextureTarget, target),
                 GLenumToString(GLESEnum::GetTextureParameter, pname), (uintptr_t)params);
    g_debug_message_insert(GL_DEBUG_SOURCE_THIRD_PARTY_KHR, GL_DEBUG_TYPE_OTHER_KHR,
                           static_cast<GLuint>(angle::EntryPoint::GLGetTexParameterxv),
                           GL_DEBUG_SEVERITY_NOTIFICATION_KHR, -1, entryPointMessage);

    // Call down to the next layer
    void *entry                     = funcMap["glGetTexParameterxv"];
    PFNGLGETTEXPARAMETERXVPROC next = reinterpret_cast<PFNGLGETTEXPARAMETERXVPROC>(entry);
    next(target, pname, params);
}

void GL_APIENTRY GL_LightModelf(GLenum pname, GLfloat param)
{
    char entryPointMessage[512];
    std::sprintf(entryPointMessage, "glLightModelf(pname = %s, param = %f)",
                 GLenumToString(GLESEnum::LightModelParameter, pname), param);
    g_debug_message_insert(GL_DEBUG_SOURCE_THIRD_PARTY_KHR, GL_DEBUG_TYPE_OTHER_KHR,
                           static_cast<GLuint>(angle::EntryPoint::GLLightModelf),
                           GL_DEBUG_SEVERITY_NOTIFICATION_KHR, -1, entryPointMessage);

    // Call down to the next layer
    void *entry               = funcMap["glLightModelf"];
    PFNGLLIGHTMODELFPROC next = reinterpret_cast<PFNGLLIGHTMODELFPROC>(entry);
    next(pname, param);
}

void GL_APIENTRY GL_LightModelfv(GLenum pname, const GLfloat *params)
{
    char entryPointMessage[512];
    std::sprintf(entryPointMessage, "glLightModelfv(pname = %s, params = 0x%016" PRIxPTR ")",
                 GLenumToString(GLESEnum::LightModelParameter, pname), (uintptr_t)params);
    g_debug_message_insert(GL_DEBUG_SOURCE_THIRD_PARTY_KHR, GL_DEBUG_TYPE_OTHER_KHR,
                           static_cast<GLuint>(angle::EntryPoint::GLLightModelfv),
                           GL_DEBUG_SEVERITY_NOTIFICATION_KHR, -1, entryPointMessage);

    // Call down to the next layer
    void *entry                = funcMap["glLightModelfv"];
    PFNGLLIGHTMODELFVPROC next = reinterpret_cast<PFNGLLIGHTMODELFVPROC>(entry);
    next(pname, params);
}

void GL_APIENTRY GL_LightModelx(GLenum pname, GLfixed param)
{
    char entryPointMessage[512];
    std::sprintf(entryPointMessage, "glLightModelx(pname = %s, param = 0x%X)",
                 GLenumToString(GLESEnum::LightModelParameter, pname), param);
    g_debug_message_insert(GL_DEBUG_SOURCE_THIRD_PARTY_KHR, GL_DEBUG_TYPE_OTHER_KHR,
                           static_cast<GLuint>(angle::EntryPoint::GLLightModelx),
                           GL_DEBUG_SEVERITY_NOTIFICATION_KHR, -1, entryPointMessage);

    // Call down to the next layer
    void *entry               = funcMap["glLightModelx"];
    PFNGLLIGHTMODELXPROC next = reinterpret_cast<PFNGLLIGHTMODELXPROC>(entry);
    next(pname, param);
}

void GL_APIENTRY GL_LightModelxv(GLenum pname, const GLfixed *param)
{
    char entryPointMessage[512];
    std::sprintf(entryPointMessage, "glLightModelxv(pname = %s, param = 0x%016" PRIxPTR ")",
                 GLenumToString(GLESEnum::LightModelParameter, pname), (uintptr_t)param);
    g_debug_message_insert(GL_DEBUG_SOURCE_THIRD_PARTY_KHR, GL_DEBUG_TYPE_OTHER_KHR,
                           static_cast<GLuint>(angle::EntryPoint::GLLightModelxv),
                           GL_DEBUG_SEVERITY_NOTIFICATION_KHR, -1, entryPointMessage);

    // Call down to the next layer
    void *entry                = funcMap["glLightModelxv"];
    PFNGLLIGHTMODELXVPROC next = reinterpret_cast<PFNGLLIGHTMODELXVPROC>(entry);
    next(pname, param);
}

void GL_APIENTRY GL_Lightf(GLenum light, GLenum pname, GLfloat param)
{
    char entryPointMessage[512];
    std::sprintf(entryPointMessage, "glLightf(light = %s, pname = %s, param = %f)",
                 GLenumToString(GLESEnum::LightName, light),
                 GLenumToString(GLESEnum::LightParameter, pname), param);
    g_debug_message_insert(GL_DEBUG_SOURCE_THIRD_PARTY_KHR, GL_DEBUG_TYPE_OTHER_KHR,
                           static_cast<GLuint>(angle::EntryPoint::GLLightf),
                           GL_DEBUG_SEVERITY_NOTIFICATION_KHR, -1, entryPointMessage);

    // Call down to the next layer
    void *entry          = funcMap["glLightf"];
    PFNGLLIGHTFPROC next = reinterpret_cast<PFNGLLIGHTFPROC>(entry);
    next(light, pname, param);
}

void GL_APIENTRY GL_Lightfv(GLenum light, GLenum pname, const GLfloat *params)
{
    char entryPointMessage[512];
    std::sprintf(entryPointMessage, "glLightfv(light = %s, pname = %s, params = 0x%016" PRIxPTR ")",
                 GLenumToString(GLESEnum::LightName, light),
                 GLenumToString(GLESEnum::LightParameter, pname), (uintptr_t)params);
    g_debug_message_insert(GL_DEBUG_SOURCE_THIRD_PARTY_KHR, GL_DEBUG_TYPE_OTHER_KHR,
                           static_cast<GLuint>(angle::EntryPoint::GLLightfv),
                           GL_DEBUG_SEVERITY_NOTIFICATION_KHR, -1, entryPointMessage);

    // Call down to the next layer
    void *entry           = funcMap["glLightfv"];
    PFNGLLIGHTFVPROC next = reinterpret_cast<PFNGLLIGHTFVPROC>(entry);
    next(light, pname, params);
}

void GL_APIENTRY GL_Lightx(GLenum light, GLenum pname, GLfixed param)
{
    char entryPointMessage[512];
    std::sprintf(entryPointMessage, "glLightx(light = %s, pname = %s, param = 0x%X)",
                 GLenumToString(GLESEnum::LightName, light),
                 GLenumToString(GLESEnum::LightParameter, pname), param);
    g_debug_message_insert(GL_DEBUG_SOURCE_THIRD_PARTY_KHR, GL_DEBUG_TYPE_OTHER_KHR,
                           static_cast<GLuint>(angle::EntryPoint::GLLightx),
                           GL_DEBUG_SEVERITY_NOTIFICATION_KHR, -1, entryPointMessage);

    // Call down to the next layer
    void *entry          = funcMap["glLightx"];
    PFNGLLIGHTXPROC next = reinterpret_cast<PFNGLLIGHTXPROC>(entry);
    next(light, pname, param);
}

void GL_APIENTRY GL_Lightxv(GLenum light, GLenum pname, const GLfixed *params)
{
    char entryPointMessage[512];
    std::sprintf(entryPointMessage, "glLightxv(light = %s, pname = %s, params = 0x%016" PRIxPTR ")",
                 GLenumToString(GLESEnum::LightName, light),
                 GLenumToString(GLESEnum::LightParameter, pname), (uintptr_t)params);
    g_debug_message_insert(GL_DEBUG_SOURCE_THIRD_PARTY_KHR, GL_DEBUG_TYPE_OTHER_KHR,
                           static_cast<GLuint>(angle::EntryPoint::GLLightxv),
                           GL_DEBUG_SEVERITY_NOTIFICATION_KHR, -1, entryPointMessage);

    // Call down to the next layer
    void *entry           = funcMap["glLightxv"];
    PFNGLLIGHTXVPROC next = reinterpret_cast<PFNGLLIGHTXVPROC>(entry);
    next(light, pname, params);
}

void GL_APIENTRY GL_LineWidthx(GLfixed width)
{
    char entryPointMessage[512];
    std::sprintf(entryPointMessage, "glLineWidthx(width = 0x%X)", width);
    g_debug_message_insert(GL_DEBUG_SOURCE_THIRD_PARTY_KHR, GL_DEBUG_TYPE_OTHER_KHR,
                           static_cast<GLuint>(angle::EntryPoint::GLLineWidthx),
                           GL_DEBUG_SEVERITY_NOTIFICATION_KHR, -1, entryPointMessage);

    // Call down to the next layer
    void *entry              = funcMap["glLineWidthx"];
    PFNGLLINEWIDTHXPROC next = reinterpret_cast<PFNGLLINEWIDTHXPROC>(entry);
    next(width);
}

void GL_APIENTRY GL_LoadIdentity()
{
    char entryPointMessage[512];
    std::sprintf(entryPointMessage, "glLoadIdentity()");
    g_debug_message_insert(GL_DEBUG_SOURCE_THIRD_PARTY_KHR, GL_DEBUG_TYPE_OTHER_KHR,
                           static_cast<GLuint>(angle::EntryPoint::GLLoadIdentity),
                           GL_DEBUG_SEVERITY_NOTIFICATION_KHR, -1, entryPointMessage);

    // Call down to the next layer
    void *entry                = funcMap["glLoadIdentity"];
    PFNGLLOADIDENTITYPROC next = reinterpret_cast<PFNGLLOADIDENTITYPROC>(entry);
    next();
}

void GL_APIENTRY GL_LoadMatrixf(const GLfloat *m)
{
    char entryPointMessage[512];
    std::sprintf(entryPointMessage, "glLoadMatrixf(m = 0x%016" PRIxPTR ")", (uintptr_t)m);
    g_debug_message_insert(GL_DEBUG_SOURCE_THIRD_PARTY_KHR, GL_DEBUG_TYPE_OTHER_KHR,
                           static_cast<GLuint>(angle::EntryPoint::GLLoadMatrixf),
                           GL_DEBUG_SEVERITY_NOTIFICATION_KHR, -1, entryPointMessage);

    // Call down to the next layer
    void *entry               = funcMap["glLoadMatrixf"];
    PFNGLLOADMATRIXFPROC next = reinterpret_cast<PFNGLLOADMATRIXFPROC>(entry);
    next(m);
}

void GL_APIENTRY GL_LoadMatrixx(const GLfixed *m)
{
    char entryPointMessage[512];
    std::sprintf(entryPointMessage, "glLoadMatrixx(m = 0x%016" PRIxPTR ")", (uintptr_t)m);
    g_debug_message_insert(GL_DEBUG_SOURCE_THIRD_PARTY_KHR, GL_DEBUG_TYPE_OTHER_KHR,
                           static_cast<GLuint>(angle::EntryPoint::GLLoadMatrixx),
                           GL_DEBUG_SEVERITY_NOTIFICATION_KHR, -1, entryPointMessage);

    // Call down to the next layer
    void *entry               = funcMap["glLoadMatrixx"];
    PFNGLLOADMATRIXXPROC next = reinterpret_cast<PFNGLLOADMATRIXXPROC>(entry);
    next(m);
}

void GL_APIENTRY GL_LogicOp(GLenum opcode)
{
    char entryPointMessage[512];
    std::sprintf(entryPointMessage, "glLogicOp(opcode = %s)",
                 GLenumToString(GLESEnum::LogicOp, opcode));
    g_debug_message_insert(GL_DEBUG_SOURCE_THIRD_PARTY_KHR, GL_DEBUG_TYPE_OTHER_KHR,
                           static_cast<GLuint>(angle::EntryPoint::GLLogicOp),
                           GL_DEBUG_SEVERITY_NOTIFICATION_KHR, -1, entryPointMessage);

    // Call down to the next layer
    void *entry           = funcMap["glLogicOp"];
    PFNGLLOGICOPPROC next = reinterpret_cast<PFNGLLOGICOPPROC>(entry);
    next(opcode);
}

void GL_APIENTRY GL_Materialf(GLenum face, GLenum pname, GLfloat param)
{
    char entryPointMessage[512];
    std::sprintf(entryPointMessage, "glMaterialf(face = %s, pname = %s, param = %f)",
                 GLenumToString(GLESEnum::MaterialFace, face),
                 GLenumToString(GLESEnum::MaterialParameter, pname), param);
    g_debug_message_insert(GL_DEBUG_SOURCE_THIRD_PARTY_KHR, GL_DEBUG_TYPE_OTHER_KHR,
                           static_cast<GLuint>(angle::EntryPoint::GLMaterialf),
                           GL_DEBUG_SEVERITY_NOTIFICATION_KHR, -1, entryPointMessage);

    // Call down to the next layer
    void *entry             = funcMap["glMaterialf"];
    PFNGLMATERIALFPROC next = reinterpret_cast<PFNGLMATERIALFPROC>(entry);
    next(face, pname, param);
}

void GL_APIENTRY GL_Materialfv(GLenum face, GLenum pname, const GLfloat *params)
{
    char entryPointMessage[512];
    std::sprintf(entryPointMessage,
                 "glMaterialfv(face = %s, pname = %s, params = 0x%016" PRIxPTR ")",
                 GLenumToString(GLESEnum::MaterialFace, face),
                 GLenumToString(GLESEnum::MaterialParameter, pname), (uintptr_t)params);
    g_debug_message_insert(GL_DEBUG_SOURCE_THIRD_PARTY_KHR, GL_DEBUG_TYPE_OTHER_KHR,
                           static_cast<GLuint>(angle::EntryPoint::GLMaterialfv),
                           GL_DEBUG_SEVERITY_NOTIFICATION_KHR, -1, entryPointMessage);

    // Call down to the next layer
    void *entry              = funcMap["glMaterialfv"];
    PFNGLMATERIALFVPROC next = reinterpret_cast<PFNGLMATERIALFVPROC>(entry);
    next(face, pname, params);
}

void GL_APIENTRY GL_Materialx(GLenum face, GLenum pname, GLfixed param)
{
    char entryPointMessage[512];
    std::sprintf(entryPointMessage, "glMaterialx(face = %s, pname = %s, param = 0x%X)",
                 GLenumToString(GLESEnum::MaterialFace, face),
                 GLenumToString(GLESEnum::MaterialParameter, pname), param);
    g_debug_message_insert(GL_DEBUG_SOURCE_THIRD_PARTY_KHR, GL_DEBUG_TYPE_OTHER_KHR,
                           static_cast<GLuint>(angle::EntryPoint::GLMaterialx),
                           GL_DEBUG_SEVERITY_NOTIFICATION_KHR, -1, entryPointMessage);

    // Call down to the next layer
    void *entry             = funcMap["glMaterialx"];
    PFNGLMATERIALXPROC next = reinterpret_cast<PFNGLMATERIALXPROC>(entry);
    next(face, pname, param);
}

void GL_APIENTRY GL_Materialxv(GLenum face, GLenum pname, const GLfixed *param)
{
    char entryPointMessage[512];
    std::sprintf(entryPointMessage,
                 "glMaterialxv(face = %s, pname = %s, param = 0x%016" PRIxPTR ")",
                 GLenumToString(GLESEnum::MaterialFace, face),
                 GLenumToString(GLESEnum::MaterialParameter, pname), (uintptr_t)param);
    g_debug_message_insert(GL_DEBUG_SOURCE_THIRD_PARTY_KHR, GL_DEBUG_TYPE_OTHER_KHR,
                           static_cast<GLuint>(angle::EntryPoint::GLMaterialxv),
                           GL_DEBUG_SEVERITY_NOTIFICATION_KHR, -1, entryPointMessage);

    // Call down to the next layer
    void *entry              = funcMap["glMaterialxv"];
    PFNGLMATERIALXVPROC next = reinterpret_cast<PFNGLMATERIALXVPROC>(entry);
    next(face, pname, param);
}

void GL_APIENTRY GL_MatrixMode(GLenum mode)
{
    char entryPointMessage[512];
    std::sprintf(entryPointMessage, "glMatrixMode(mode = %s)",
                 GLenumToString(GLESEnum::MatrixMode, mode));
    g_debug_message_insert(GL_DEBUG_SOURCE_THIRD_PARTY_KHR, GL_DEBUG_TYPE_OTHER_KHR,
                           static_cast<GLuint>(angle::EntryPoint::GLMatrixMode),
                           GL_DEBUG_SEVERITY_NOTIFICATION_KHR, -1, entryPointMessage);

    // Call down to the next layer
    void *entry              = funcMap["glMatrixMode"];
    PFNGLMATRIXMODEPROC next = reinterpret_cast<PFNGLMATRIXMODEPROC>(entry);
    next(mode);
}

void GL_APIENTRY GL_MultMatrixf(const GLfloat *m)
{
    char entryPointMessage[512];
    std::sprintf(entryPointMessage, "glMultMatrixf(m = 0x%016" PRIxPTR ")", (uintptr_t)m);
    g_debug_message_insert(GL_DEBUG_SOURCE_THIRD_PARTY_KHR, GL_DEBUG_TYPE_OTHER_KHR,
                           static_cast<GLuint>(angle::EntryPoint::GLMultMatrixf),
                           GL_DEBUG_SEVERITY_NOTIFICATION_KHR, -1, entryPointMessage);

    // Call down to the next layer
    void *entry               = funcMap["glMultMatrixf"];
    PFNGLMULTMATRIXFPROC next = reinterpret_cast<PFNGLMULTMATRIXFPROC>(entry);
    next(m);
}

void GL_APIENTRY GL_MultMatrixx(const GLfixed *m)
{
    char entryPointMessage[512];
    std::sprintf(entryPointMessage, "glMultMatrixx(m = 0x%016" PRIxPTR ")", (uintptr_t)m);
    g_debug_message_insert(GL_DEBUG_SOURCE_THIRD_PARTY_KHR, GL_DEBUG_TYPE_OTHER_KHR,
                           static_cast<GLuint>(angle::EntryPoint::GLMultMatrixx),
                           GL_DEBUG_SEVERITY_NOTIFICATION_KHR, -1, entryPointMessage);

    // Call down to the next layer
    void *entry               = funcMap["glMultMatrixx"];
    PFNGLMULTMATRIXXPROC next = reinterpret_cast<PFNGLMULTMATRIXXPROC>(entry);
    next(m);
}

void GL_APIENTRY GL_MultiTexCoord4f(GLenum target, GLfloat s, GLfloat t, GLfloat r, GLfloat q)
{
    char entryPointMessage[512];
    std::sprintf(entryPointMessage,
                 "glMultiTexCoord4f(target = %s, s = %f, t = %f, r = %f, q = %f)",
                 GLenumToString(GLESEnum::TextureUnit, target), s, t, r, q);
    g_debug_message_insert(GL_DEBUG_SOURCE_THIRD_PARTY_KHR, GL_DEBUG_TYPE_OTHER_KHR,
                           static_cast<GLuint>(angle::EntryPoint::GLMultiTexCoord4f),
                           GL_DEBUG_SEVERITY_NOTIFICATION_KHR, -1, entryPointMessage);

    // Call down to the next layer
    void *entry                   = funcMap["glMultiTexCoord4f"];
    PFNGLMULTITEXCOORD4FPROC next = reinterpret_cast<PFNGLMULTITEXCOORD4FPROC>(entry);
    next(target, s, t, r, q);
}

void GL_APIENTRY GL_MultiTexCoord4x(GLenum texture, GLfixed s, GLfixed t, GLfixed r, GLfixed q)
{
    char entryPointMessage[512];
    std::sprintf(entryPointMessage,
                 "glMultiTexCoord4x(texture = %s, s = 0x%X, t = 0x%X, r = 0x%X, q = 0x%X)",
                 GLenumToString(GLESEnum::TextureUnit, texture), s, t, r, q);
    g_debug_message_insert(GL_DEBUG_SOURCE_THIRD_PARTY_KHR, GL_DEBUG_TYPE_OTHER_KHR,
                           static_cast<GLuint>(angle::EntryPoint::GLMultiTexCoord4x),
                           GL_DEBUG_SEVERITY_NOTIFICATION_KHR, -1, entryPointMessage);

    // Call down to the next layer
    void *entry                   = funcMap["glMultiTexCoord4x"];
    PFNGLMULTITEXCOORD4XPROC next = reinterpret_cast<PFNGLMULTITEXCOORD4XPROC>(entry);
    next(texture, s, t, r, q);
}

void GL_APIENTRY GL_Normal3f(GLfloat nx, GLfloat ny, GLfloat nz)
{
    char entryPointMessage[512];
    std::sprintf(entryPointMessage, "glNormal3f(nx = %f, ny = %f, nz = %f)", nx, ny, nz);
    g_debug_message_insert(GL_DEBUG_SOURCE_THIRD_PARTY_KHR, GL_DEBUG_TYPE_OTHER_KHR,
                           static_cast<GLuint>(angle::EntryPoint::GLNormal3f),
                           GL_DEBUG_SEVERITY_NOTIFICATION_KHR, -1, entryPointMessage);

    // Call down to the next layer
    void *entry            = funcMap["glNormal3f"];
    PFNGLNORMAL3FPROC next = reinterpret_cast<PFNGLNORMAL3FPROC>(entry);
    next(nx, ny, nz);
}

void GL_APIENTRY GL_Normal3x(GLfixed nx, GLfixed ny, GLfixed nz)
{
    char entryPointMessage[512];
    std::sprintf(entryPointMessage, "glNormal3x(nx = 0x%X, ny = 0x%X, nz = 0x%X)", nx, ny, nz);
    g_debug_message_insert(GL_DEBUG_SOURCE_THIRD_PARTY_KHR, GL_DEBUG_TYPE_OTHER_KHR,
                           static_cast<GLuint>(angle::EntryPoint::GLNormal3x),
                           GL_DEBUG_SEVERITY_NOTIFICATION_KHR, -1, entryPointMessage);

    // Call down to the next layer
    void *entry            = funcMap["glNormal3x"];
    PFNGLNORMAL3XPROC next = reinterpret_cast<PFNGLNORMAL3XPROC>(entry);
    next(nx, ny, nz);
}

void GL_APIENTRY GL_NormalPointer(GLenum type, GLsizei stride, const void *pointer)
{
    char entryPointMessage[512];
    std::sprintf(entryPointMessage,
                 "glNormalPointer(type = %s, stride = %d, pointer = 0x%016" PRIxPTR ")",
                 GLenumToString(GLESEnum::NormalPointerType, type), stride, (uintptr_t)pointer);
    g_debug_message_insert(GL_DEBUG_SOURCE_THIRD_PARTY_KHR, GL_DEBUG_TYPE_OTHER_KHR,
                           static_cast<GLuint>(angle::EntryPoint::GLNormalPointer),
                           GL_DEBUG_SEVERITY_NOTIFICATION_KHR, -1, entryPointMessage);

    // Call down to the next layer
    void *entry                 = funcMap["glNormalPointer"];
    PFNGLNORMALPOINTERPROC next = reinterpret_cast<PFNGLNORMALPOINTERPROC>(entry);
    next(type, stride, pointer);
}

void GL_APIENTRY GL_Orthof(GLfloat l, GLfloat r, GLfloat b, GLfloat t, GLfloat n, GLfloat f)
{
    char entryPointMessage[512];
    std::sprintf(entryPointMessage, "glOrthof(l = %f, r = %f, b = %f, t = %f, n = %f, f = %f)", l,
                 r, b, t, n, f);
    g_debug_message_insert(GL_DEBUG_SOURCE_THIRD_PARTY_KHR, GL_DEBUG_TYPE_OTHER_KHR,
                           static_cast<GLuint>(angle::EntryPoint::GLOrthof),
                           GL_DEBUG_SEVERITY_NOTIFICATION_KHR, -1, entryPointMessage);

    // Call down to the next layer
    void *entry          = funcMap["glOrthof"];
    PFNGLORTHOFPROC next = reinterpret_cast<PFNGLORTHOFPROC>(entry);
    next(l, r, b, t, n, f);
}

void GL_APIENTRY GL_Orthox(GLfixed l, GLfixed r, GLfixed b, GLfixed t, GLfixed n, GLfixed f)
{
    char entryPointMessage[512];
    std::sprintf(entryPointMessage,
                 "glOrthox(l = 0x%X, r = 0x%X, b = 0x%X, t = 0x%X, n = 0x%X, f = 0x%X)", l, r, b, t,
                 n, f);
    g_debug_message_insert(GL_DEBUG_SOURCE_THIRD_PARTY_KHR, GL_DEBUG_TYPE_OTHER_KHR,
                           static_cast<GLuint>(angle::EntryPoint::GLOrthox),
                           GL_DEBUG_SEVERITY_NOTIFICATION_KHR, -1, entryPointMessage);

    // Call down to the next layer
    void *entry          = funcMap["glOrthox"];
    PFNGLORTHOXPROC next = reinterpret_cast<PFNGLORTHOXPROC>(entry);
    next(l, r, b, t, n, f);
}

void GL_APIENTRY GL_PointParameterf(GLenum pname, GLfloat param)
{
    char entryPointMessage[512];
    std::sprintf(entryPointMessage, "glPointParameterf(pname = %s, param = %f)",
                 GLenumToString(GLESEnum::AllEnums, pname), param);
    g_debug_message_insert(GL_DEBUG_SOURCE_THIRD_PARTY_KHR, GL_DEBUG_TYPE_OTHER_KHR,
                           static_cast<GLuint>(angle::EntryPoint::GLPointParameterf),
                           GL_DEBUG_SEVERITY_NOTIFICATION_KHR, -1, entryPointMessage);

    // Call down to the next layer
    void *entry                   = funcMap["glPointParameterf"];
    PFNGLPOINTPARAMETERFPROC next = reinterpret_cast<PFNGLPOINTPARAMETERFPROC>(entry);
    next(pname, param);
}

void GL_APIENTRY GL_PointParameterfv(GLenum pname, const GLfloat *params)
{
    char entryPointMessage[512];
    std::sprintf(entryPointMessage, "glPointParameterfv(pname = %s, params = 0x%016" PRIxPTR ")",
                 GLenumToString(GLESEnum::AllEnums, pname), (uintptr_t)params);
    g_debug_message_insert(GL_DEBUG_SOURCE_THIRD_PARTY_KHR, GL_DEBUG_TYPE_OTHER_KHR,
                           static_cast<GLuint>(angle::EntryPoint::GLPointParameterfv),
                           GL_DEBUG_SEVERITY_NOTIFICATION_KHR, -1, entryPointMessage);

    // Call down to the next layer
    void *entry                    = funcMap["glPointParameterfv"];
    PFNGLPOINTPARAMETERFVPROC next = reinterpret_cast<PFNGLPOINTPARAMETERFVPROC>(entry);
    next(pname, params);
}

void GL_APIENTRY GL_PointParameterx(GLenum pname, GLfixed param)
{
    char entryPointMessage[512];
    std::sprintf(entryPointMessage, "glPointParameterx(pname = %s, param = 0x%X)",
                 GLenumToString(GLESEnum::AllEnums, pname), param);
    g_debug_message_insert(GL_DEBUG_SOURCE_THIRD_PARTY_KHR, GL_DEBUG_TYPE_OTHER_KHR,
                           static_cast<GLuint>(angle::EntryPoint::GLPointParameterx),
                           GL_DEBUG_SEVERITY_NOTIFICATION_KHR, -1, entryPointMessage);

    // Call down to the next layer
    void *entry                   = funcMap["glPointParameterx"];
    PFNGLPOINTPARAMETERXPROC next = reinterpret_cast<PFNGLPOINTPARAMETERXPROC>(entry);
    next(pname, param);
}

void GL_APIENTRY GL_PointParameterxv(GLenum pname, const GLfixed *params)
{
    char entryPointMessage[512];
    std::sprintf(entryPointMessage, "glPointParameterxv(pname = %s, params = 0x%016" PRIxPTR ")",
                 GLenumToString(GLESEnum::AllEnums, pname), (uintptr_t)params);
    g_debug_message_insert(GL_DEBUG_SOURCE_THIRD_PARTY_KHR, GL_DEBUG_TYPE_OTHER_KHR,
                           static_cast<GLuint>(angle::EntryPoint::GLPointParameterxv),
                           GL_DEBUG_SEVERITY_NOTIFICATION_KHR, -1, entryPointMessage);

    // Call down to the next layer
    void *entry                    = funcMap["glPointParameterxv"];
    PFNGLPOINTPARAMETERXVPROC next = reinterpret_cast<PFNGLPOINTPARAMETERXVPROC>(entry);
    next(pname, params);
}

void GL_APIENTRY GL_PointSize(GLfloat size)
{
    char entryPointMessage[512];
    std::sprintf(entryPointMessage, "glPointSize(size = %f)", size);
    g_debug_message_insert(GL_DEBUG_SOURCE_THIRD_PARTY_KHR, GL_DEBUG_TYPE_OTHER_KHR,
                           static_cast<GLuint>(angle::EntryPoint::GLPointSize),
                           GL_DEBUG_SEVERITY_NOTIFICATION_KHR, -1, entryPointMessage);

    // Call down to the next layer
    void *entry             = funcMap["glPointSize"];
    PFNGLPOINTSIZEPROC next = reinterpret_cast<PFNGLPOINTSIZEPROC>(entry);
    next(size);
}

void GL_APIENTRY GL_PointSizex(GLfixed size)
{
    char entryPointMessage[512];
    std::sprintf(entryPointMessage, "glPointSizex(size = 0x%X)", size);
    g_debug_message_insert(GL_DEBUG_SOURCE_THIRD_PARTY_KHR, GL_DEBUG_TYPE_OTHER_KHR,
                           static_cast<GLuint>(angle::EntryPoint::GLPointSizex),
                           GL_DEBUG_SEVERITY_NOTIFICATION_KHR, -1, entryPointMessage);

    // Call down to the next layer
    void *entry              = funcMap["glPointSizex"];
    PFNGLPOINTSIZEXPROC next = reinterpret_cast<PFNGLPOINTSIZEXPROC>(entry);
    next(size);
}

void GL_APIENTRY GL_PolygonOffsetx(GLfixed factor, GLfixed units)
{
    char entryPointMessage[512];
    std::sprintf(entryPointMessage, "glPolygonOffsetx(factor = 0x%X, units = 0x%X)", factor, units);
    g_debug_message_insert(GL_DEBUG_SOURCE_THIRD_PARTY_KHR, GL_DEBUG_TYPE_OTHER_KHR,
                           static_cast<GLuint>(angle::EntryPoint::GLPolygonOffsetx),
                           GL_DEBUG_SEVERITY_NOTIFICATION_KHR, -1, entryPointMessage);

    // Call down to the next layer
    void *entry                  = funcMap["glPolygonOffsetx"];
    PFNGLPOLYGONOFFSETXPROC next = reinterpret_cast<PFNGLPOLYGONOFFSETXPROC>(entry);
    next(factor, units);
}

void GL_APIENTRY GL_PopMatrix()
{
    char entryPointMessage[512];
    std::sprintf(entryPointMessage, "glPopMatrix()");
    g_debug_message_insert(GL_DEBUG_SOURCE_THIRD_PARTY_KHR, GL_DEBUG_TYPE_OTHER_KHR,
                           static_cast<GLuint>(angle::EntryPoint::GLPopMatrix),
                           GL_DEBUG_SEVERITY_NOTIFICATION_KHR, -1, entryPointMessage);

    // Call down to the next layer
    void *entry             = funcMap["glPopMatrix"];
    PFNGLPOPMATRIXPROC next = reinterpret_cast<PFNGLPOPMATRIXPROC>(entry);
    next();
}

void GL_APIENTRY GL_PushMatrix()
{
    char entryPointMessage[512];
    std::sprintf(entryPointMessage, "glPushMatrix()");
    g_debug_message_insert(GL_DEBUG_SOURCE_THIRD_PARTY_KHR, GL_DEBUG_TYPE_OTHER_KHR,
                           static_cast<GLuint>(angle::EntryPoint::GLPushMatrix),
                           GL_DEBUG_SEVERITY_NOTIFICATION_KHR, -1, entryPointMessage);

    // Call down to the next layer
    void *entry              = funcMap["glPushMatrix"];
    PFNGLPUSHMATRIXPROC next = reinterpret_cast<PFNGLPUSHMATRIXPROC>(entry);
    next();
}

void GL_APIENTRY GL_Rotatef(GLfloat angle, GLfloat x, GLfloat y, GLfloat z)
{
    char entryPointMessage[512];
    std::sprintf(entryPointMessage, "glRotatef(angle = %f, x = %f, y = %f, z = %f)", angle, x, y,
                 z);
    g_debug_message_insert(GL_DEBUG_SOURCE_THIRD_PARTY_KHR, GL_DEBUG_TYPE_OTHER_KHR,
                           static_cast<GLuint>(angle::EntryPoint::GLRotatef),
                           GL_DEBUG_SEVERITY_NOTIFICATION_KHR, -1, entryPointMessage);

    // Call down to the next layer
    void *entry           = funcMap["glRotatef"];
    PFNGLROTATEFPROC next = reinterpret_cast<PFNGLROTATEFPROC>(entry);
    next(angle, x, y, z);
}

void GL_APIENTRY GL_Rotatex(GLfixed angle, GLfixed x, GLfixed y, GLfixed z)
{
    char entryPointMessage[512];
    std::sprintf(entryPointMessage, "glRotatex(angle = 0x%X, x = 0x%X, y = 0x%X, z = 0x%X)", angle,
                 x, y, z);
    g_debug_message_insert(GL_DEBUG_SOURCE_THIRD_PARTY_KHR, GL_DEBUG_TYPE_OTHER_KHR,
                           static_cast<GLuint>(angle::EntryPoint::GLRotatex),
                           GL_DEBUG_SEVERITY_NOTIFICATION_KHR, -1, entryPointMessage);

    // Call down to the next layer
    void *entry           = funcMap["glRotatex"];
    PFNGLROTATEXPROC next = reinterpret_cast<PFNGLROTATEXPROC>(entry);
    next(angle, x, y, z);
}

void GL_APIENTRY GL_SampleCoveragex(GLclampx value, GLboolean invert)
{
    char entryPointMessage[512];
    std::sprintf(entryPointMessage, "glSampleCoveragex(value = 0x%X, invert = %s)", value,
                 GLbooleanToString(invert));
    g_debug_message_insert(GL_DEBUG_SOURCE_THIRD_PARTY_KHR, GL_DEBUG_TYPE_OTHER_KHR,
                           static_cast<GLuint>(angle::EntryPoint::GLSampleCoveragex),
                           GL_DEBUG_SEVERITY_NOTIFICATION_KHR, -1, entryPointMessage);

    // Call down to the next layer
    void *entry                   = funcMap["glSampleCoveragex"];
    PFNGLSAMPLECOVERAGEXPROC next = reinterpret_cast<PFNGLSAMPLECOVERAGEXPROC>(entry);
    next(value, invert);
}

void GL_APIENTRY GL_Scalef(GLfloat x, GLfloat y, GLfloat z)
{
    char entryPointMessage[512];
    std::sprintf(entryPointMessage, "glScalef(x = %f, y = %f, z = %f)", x, y, z);
    g_debug_message_insert(GL_DEBUG_SOURCE_THIRD_PARTY_KHR, GL_DEBUG_TYPE_OTHER_KHR,
                           static_cast<GLuint>(angle::EntryPoint::GLScalef),
                           GL_DEBUG_SEVERITY_NOTIFICATION_KHR, -1, entryPointMessage);

    // Call down to the next layer
    void *entry          = funcMap["glScalef"];
    PFNGLSCALEFPROC next = reinterpret_cast<PFNGLSCALEFPROC>(entry);
    next(x, y, z);
}

void GL_APIENTRY GL_Scalex(GLfixed x, GLfixed y, GLfixed z)
{
    char entryPointMessage[512];
    std::sprintf(entryPointMessage, "glScalex(x = 0x%X, y = 0x%X, z = 0x%X)", x, y, z);
    g_debug_message_insert(GL_DEBUG_SOURCE_THIRD_PARTY_KHR, GL_DEBUG_TYPE_OTHER_KHR,
                           static_cast<GLuint>(angle::EntryPoint::GLScalex),
                           GL_DEBUG_SEVERITY_NOTIFICATION_KHR, -1, entryPointMessage);

    // Call down to the next layer
    void *entry          = funcMap["glScalex"];
    PFNGLSCALEXPROC next = reinterpret_cast<PFNGLSCALEXPROC>(entry);
    next(x, y, z);
}

void GL_APIENTRY GL_ShadeModel(GLenum mode)
{
    char entryPointMessage[512];
    std::sprintf(entryPointMessage, "glShadeModel(mode = %s)",
                 GLenumToString(GLESEnum::ShadingModel, mode));
    g_debug_message_insert(GL_DEBUG_SOURCE_THIRD_PARTY_KHR, GL_DEBUG_TYPE_OTHER_KHR,
                           static_cast<GLuint>(angle::EntryPoint::GLShadeModel),
                           GL_DEBUG_SEVERITY_NOTIFICATION_KHR, -1, entryPointMessage);

    // Call down to the next layer
    void *entry              = funcMap["glShadeModel"];
    PFNGLSHADEMODELPROC next = reinterpret_cast<PFNGLSHADEMODELPROC>(entry);
    next(mode);
}

void GL_APIENTRY GL_TexCoordPointer(GLint size, GLenum type, GLsizei stride, const void *pointer)
{
    char entryPointMessage[512];
    std::sprintf(
        entryPointMessage,
        "glTexCoordPointer(size = %d, type = %s, stride = %d, pointer = 0x%016" PRIxPTR ")", size,
        GLenumToString(GLESEnum::TexCoordPointerType, type), stride, (uintptr_t)pointer);
    g_debug_message_insert(GL_DEBUG_SOURCE_THIRD_PARTY_KHR, GL_DEBUG_TYPE_OTHER_KHR,
                           static_cast<GLuint>(angle::EntryPoint::GLTexCoordPointer),
                           GL_DEBUG_SEVERITY_NOTIFICATION_KHR, -1, entryPointMessage);

    // Call down to the next layer
    void *entry                   = funcMap["glTexCoordPointer"];
    PFNGLTEXCOORDPOINTERPROC next = reinterpret_cast<PFNGLTEXCOORDPOINTERPROC>(entry);
    next(size, type, stride, pointer);
}

void GL_APIENTRY GL_TexEnvf(GLenum target, GLenum pname, GLfloat param)
{
    char entryPointMessage[512];
    std::sprintf(entryPointMessage, "glTexEnvf(target = %s, pname = %s, param = %f)",
                 GLenumToString(GLESEnum::TextureEnvTarget, target),
                 GLenumToString(GLESEnum::TextureEnvParameter, pname), param);
    g_debug_message_insert(GL_DEBUG_SOURCE_THIRD_PARTY_KHR, GL_DEBUG_TYPE_OTHER_KHR,
                           static_cast<GLuint>(angle::EntryPoint::GLTexEnvf),
                           GL_DEBUG_SEVERITY_NOTIFICATION_KHR, -1, entryPointMessage);

    // Call down to the next layer
    void *entry           = funcMap["glTexEnvf"];
    PFNGLTEXENVFPROC next = reinterpret_cast<PFNGLTEXENVFPROC>(entry);
    next(target, pname, param);
}

void GL_APIENTRY GL_TexEnvfv(GLenum target, GLenum pname, const GLfloat *params)
{
    char entryPointMessage[512];
    std::sprintf(entryPointMessage,
                 "glTexEnvfv(target = %s, pname = %s, params = 0x%016" PRIxPTR ")",
                 GLenumToString(GLESEnum::TextureEnvTarget, target),
                 GLenumToString(GLESEnum::TextureEnvParameter, pname), (uintptr_t)params);
    g_debug_message_insert(GL_DEBUG_SOURCE_THIRD_PARTY_KHR, GL_DEBUG_TYPE_OTHER_KHR,
                           static_cast<GLuint>(angle::EntryPoint::GLTexEnvfv),
                           GL_DEBUG_SEVERITY_NOTIFICATION_KHR, -1, entryPointMessage);

    // Call down to the next layer
    void *entry            = funcMap["glTexEnvfv"];
    PFNGLTEXENVFVPROC next = reinterpret_cast<PFNGLTEXENVFVPROC>(entry);
    next(target, pname, params);
}

void GL_APIENTRY GL_TexEnvi(GLenum target, GLenum pname, GLint param)
{
    char entryPointMessage[512];
    std::sprintf(entryPointMessage, "glTexEnvi(target = %s, pname = %s, param = %d)",
                 GLenumToString(GLESEnum::TextureEnvTarget, target),
                 GLenumToString(GLESEnum::TextureEnvParameter, pname), param);
    g_debug_message_insert(GL_DEBUG_SOURCE_THIRD_PARTY_KHR, GL_DEBUG_TYPE_OTHER_KHR,
                           static_cast<GLuint>(angle::EntryPoint::GLTexEnvi),
                           GL_DEBUG_SEVERITY_NOTIFICATION_KHR, -1, entryPointMessage);

    // Call down to the next layer
    void *entry           = funcMap["glTexEnvi"];
    PFNGLTEXENVIPROC next = reinterpret_cast<PFNGLTEXENVIPROC>(entry);
    next(target, pname, param);
}

void GL_APIENTRY GL_TexEnviv(GLenum target, GLenum pname, const GLint *params)
{
    char entryPointMessage[512];
    std::sprintf(entryPointMessage,
                 "glTexEnviv(target = %s, pname = %s, params = 0x%016" PRIxPTR ")",
                 GLenumToString(GLESEnum::TextureEnvTarget, target),
                 GLenumToString(GLESEnum::TextureEnvParameter, pname), (uintptr_t)params);
    g_debug_message_insert(GL_DEBUG_SOURCE_THIRD_PARTY_KHR, GL_DEBUG_TYPE_OTHER_KHR,
                           static_cast<GLuint>(angle::EntryPoint::GLTexEnviv),
                           GL_DEBUG_SEVERITY_NOTIFICATION_KHR, -1, entryPointMessage);

    // Call down to the next layer
    void *entry            = funcMap["glTexEnviv"];
    PFNGLTEXENVIVPROC next = reinterpret_cast<PFNGLTEXENVIVPROC>(entry);
    next(target, pname, params);
}

void GL_APIENTRY GL_TexEnvx(GLenum target, GLenum pname, GLfixed param)
{
    char entryPointMessage[512];
    std::sprintf(entryPointMessage, "glTexEnvx(target = %s, pname = %s, param = 0x%X)",
                 GLenumToString(GLESEnum::TextureEnvTarget, target),
                 GLenumToString(GLESEnum::TextureEnvParameter, pname), param);
    g_debug_message_insert(GL_DEBUG_SOURCE_THIRD_PARTY_KHR, GL_DEBUG_TYPE_OTHER_KHR,
                           static_cast<GLuint>(angle::EntryPoint::GLTexEnvx),
                           GL_DEBUG_SEVERITY_NOTIFICATION_KHR, -1, entryPointMessage);

    // Call down to the next layer
    void *entry           = funcMap["glTexEnvx"];
    PFNGLTEXENVXPROC next = reinterpret_cast<PFNGLTEXENVXPROC>(entry);
    next(target, pname, param);
}

void GL_APIENTRY GL_TexEnvxv(GLenum target, GLenum pname, const GLfixed *params)
{
    char entryPointMessage[512];
    std::sprintf(entryPointMessage,
                 "glTexEnvxv(target = %s, pname = %s, params = 0x%016" PRIxPTR ")",
                 GLenumToString(GLESEnum::TextureEnvTarget, target),
                 GLenumToString(GLESEnum::TextureEnvParameter, pname), (uintptr_t)params);
    g_debug_message_insert(GL_DEBUG_SOURCE_THIRD_PARTY_KHR, GL_DEBUG_TYPE_OTHER_KHR,
                           static_cast<GLuint>(angle::EntryPoint::GLTexEnvxv),
                           GL_DEBUG_SEVERITY_NOTIFICATION_KHR, -1, entryPointMessage);

    // Call down to the next layer
    void *entry            = funcMap["glTexEnvxv"];
    PFNGLTEXENVXVPROC next = reinterpret_cast<PFNGLTEXENVXVPROC>(entry);
    next(target, pname, params);
}

void GL_APIENTRY GL_TexParameterx(GLenum target, GLenum pname, GLfixed param)
{
    char entryPointMessage[512];
    std::sprintf(entryPointMessage, "glTexParameterx(target = %s, pname = %s, param = 0x%X)",
                 GLenumToString(GLESEnum::TextureTarget, target),
                 GLenumToString(GLESEnum::GetTextureParameter, pname), param);
    g_debug_message_insert(GL_DEBUG_SOURCE_THIRD_PARTY_KHR, GL_DEBUG_TYPE_OTHER_KHR,
                           static_cast<GLuint>(angle::EntryPoint::GLTexParameterx),
                           GL_DEBUG_SEVERITY_NOTIFICATION_KHR, -1, entryPointMessage);

    // Call down to the next layer
    void *entry                 = funcMap["glTexParameterx"];
    PFNGLTEXPARAMETERXPROC next = reinterpret_cast<PFNGLTEXPARAMETERXPROC>(entry);
    next(target, pname, param);
}

void GL_APIENTRY GL_TexParameterxv(GLenum target, GLenum pname, const GLfixed *params)
{
    char entryPointMessage[512];
    std::sprintf(entryPointMessage,
                 "glTexParameterxv(target = %s, pname = %s, params = 0x%016" PRIxPTR ")",
                 GLenumToString(GLESEnum::TextureTarget, target),
                 GLenumToString(GLESEnum::GetTextureParameter, pname), (uintptr_t)params);
    g_debug_message_insert(GL_DEBUG_SOURCE_THIRD_PARTY_KHR, GL_DEBUG_TYPE_OTHER_KHR,
                           static_cast<GLuint>(angle::EntryPoint::GLTexParameterxv),
                           GL_DEBUG_SEVERITY_NOTIFICATION_KHR, -1, entryPointMessage);

    // Call down to the next layer
    void *entry                  = funcMap["glTexParameterxv"];
    PFNGLTEXPARAMETERXVPROC next = reinterpret_cast<PFNGLTEXPARAMETERXVPROC>(entry);
    next(target, pname, params);
}

void GL_APIENTRY GL_Translatef(GLfloat x, GLfloat y, GLfloat z)
{
    char entryPointMessage[512];
    std::sprintf(entryPointMessage, "glTranslatef(x = %f, y = %f, z = %f)", x, y, z);
    g_debug_message_insert(GL_DEBUG_SOURCE_THIRD_PARTY_KHR, GL_DEBUG_TYPE_OTHER_KHR,
                           static_cast<GLuint>(angle::EntryPoint::GLTranslatef),
                           GL_DEBUG_SEVERITY_NOTIFICATION_KHR, -1, entryPointMessage);

    // Call down to the next layer
    void *entry              = funcMap["glTranslatef"];
    PFNGLTRANSLATEFPROC next = reinterpret_cast<PFNGLTRANSLATEFPROC>(entry);
    next(x, y, z);
}

void GL_APIENTRY GL_Translatex(GLfixed x, GLfixed y, GLfixed z)
{
    char entryPointMessage[512];
    std::sprintf(entryPointMessage, "glTranslatex(x = 0x%X, y = 0x%X, z = 0x%X)", x, y, z);
    g_debug_message_insert(GL_DEBUG_SOURCE_THIRD_PARTY_KHR, GL_DEBUG_TYPE_OTHER_KHR,
                           static_cast<GLuint>(angle::EntryPoint::GLTranslatex),
                           GL_DEBUG_SEVERITY_NOTIFICATION_KHR, -1, entryPointMessage);

    // Call down to the next layer
    void *entry              = funcMap["glTranslatex"];
    PFNGLTRANSLATEXPROC next = reinterpret_cast<PFNGLTRANSLATEXPROC>(entry);
    next(x, y, z);
}

void GL_APIENTRY GL_VertexPointer(GLint size, GLenum type, GLsizei stride, const void *pointer)
{
    char entryPointMessage[512];
    std::sprintf(entryPointMessage,
                 "glVertexPointer(size = %d, type = %s, stride = %d, pointer = 0x%016" PRIxPTR ")",
                 size, GLenumToString(GLESEnum::VertexPointerType, type), stride,
                 (uintptr_t)pointer);
    g_debug_message_insert(GL_DEBUG_SOURCE_THIRD_PARTY_KHR, GL_DEBUG_TYPE_OTHER_KHR,
                           static_cast<GLuint>(angle::EntryPoint::GLVertexPointer),
                           GL_DEBUG_SEVERITY_NOTIFICATION_KHR, -1, entryPointMessage);

    // Call down to the next layer
    void *entry                 = funcMap["glVertexPointer"];
    PFNGLVERTEXPOINTERPROC next = reinterpret_cast<PFNGLVERTEXPOINTERPROC>(entry);
    next(size, type, stride, pointer);
}

void setupGLES_1_0Hooks()
{
    hookMap["glAlphaFunc"]           = (void *)GL_AlphaFunc;
    hookMap["glAlphaFuncx"]          = (void *)GL_AlphaFuncx;
    hookMap["glClearColorx"]         = (void *)GL_ClearColorx;
    hookMap["glClearDepthx"]         = (void *)GL_ClearDepthx;
    hookMap["glClientActiveTexture"] = (void *)GL_ClientActiveTexture;
    hookMap["glClipPlanef"]          = (void *)GL_ClipPlanef;
    hookMap["glClipPlanex"]          = (void *)GL_ClipPlanex;
    hookMap["glColor4f"]             = (void *)GL_Color4f;
    hookMap["glColor4ub"]            = (void *)GL_Color4ub;
    hookMap["glColor4x"]             = (void *)GL_Color4x;
    hookMap["glColorPointer"]        = (void *)GL_ColorPointer;
    hookMap["glDepthRangex"]         = (void *)GL_DepthRangex;
    hookMap["glDisableClientState"]  = (void *)GL_DisableClientState;
    hookMap["glEnableClientState"]   = (void *)GL_EnableClientState;
    hookMap["glFogf"]                = (void *)GL_Fogf;
    hookMap["glFogfv"]               = (void *)GL_Fogfv;
    hookMap["glFogx"]                = (void *)GL_Fogx;
    hookMap["glFogxv"]               = (void *)GL_Fogxv;
    hookMap["glFrustumf"]            = (void *)GL_Frustumf;
    hookMap["glFrustumx"]            = (void *)GL_Frustumx;
    hookMap["glGetClipPlanef"]       = (void *)GL_GetClipPlanef;
    hookMap["glGetClipPlanex"]       = (void *)GL_GetClipPlanex;
    hookMap["glGetFixedv"]           = (void *)GL_GetFixedv;
    hookMap["glGetLightfv"]          = (void *)GL_GetLightfv;
    hookMap["glGetLightxv"]          = (void *)GL_GetLightxv;
    hookMap["glGetMaterialfv"]       = (void *)GL_GetMaterialfv;
    hookMap["glGetMaterialxv"]       = (void *)GL_GetMaterialxv;
    hookMap["glGetTexEnvfv"]         = (void *)GL_GetTexEnvfv;
    hookMap["glGetTexEnviv"]         = (void *)GL_GetTexEnviv;
    hookMap["glGetTexEnvxv"]         = (void *)GL_GetTexEnvxv;
    hookMap["glGetTexParameterxv"]   = (void *)GL_GetTexParameterxv;
    hookMap["glLightModelf"]         = (void *)GL_LightModelf;
    hookMap["glLightModelfv"]        = (void *)GL_LightModelfv;
    hookMap["glLightModelx"]         = (void *)GL_LightModelx;
    hookMap["glLightModelxv"]        = (void *)GL_LightModelxv;
    hookMap["glLightf"]              = (void *)GL_Lightf;
    hookMap["glLightfv"]             = (void *)GL_Lightfv;
    hookMap["glLightx"]              = (void *)GL_Lightx;
    hookMap["glLightxv"]             = (void *)GL_Lightxv;
    hookMap["glLineWidthx"]          = (void *)GL_LineWidthx;
    hookMap["glLoadIdentity"]        = (void *)GL_LoadIdentity;
    hookMap["glLoadMatrixf"]         = (void *)GL_LoadMatrixf;
    hookMap["glLoadMatrixx"]         = (void *)GL_LoadMatrixx;
    hookMap["glLogicOp"]             = (void *)GL_LogicOp;
    hookMap["glMaterialf"]           = (void *)GL_Materialf;
    hookMap["glMaterialfv"]          = (void *)GL_Materialfv;
    hookMap["glMaterialx"]           = (void *)GL_Materialx;
    hookMap["glMaterialxv"]          = (void *)GL_Materialxv;
    hookMap["glMatrixMode"]          = (void *)GL_MatrixMode;
    hookMap["glMultMatrixf"]         = (void *)GL_MultMatrixf;
    hookMap["glMultMatrixx"]         = (void *)GL_MultMatrixx;
    hookMap["glMultiTexCoord4f"]     = (void *)GL_MultiTexCoord4f;
    hookMap["glMultiTexCoord4x"]     = (void *)GL_MultiTexCoord4x;
    hookMap["glNormal3f"]            = (void *)GL_Normal3f;
    hookMap["glNormal3x"]            = (void *)GL_Normal3x;
    hookMap["glNormalPointer"]       = (void *)GL_NormalPointer;
    hookMap["glOrthof"]              = (void *)GL_Orthof;
    hookMap["glOrthox"]              = (void *)GL_Orthox;
    hookMap["glPointParameterf"]     = (void *)GL_PointParameterf;
    hookMap["glPointParameterfv"]    = (void *)GL_PointParameterfv;
    hookMap["glPointParameterx"]     = (void *)GL_PointParameterx;
    hookMap["glPointParameterxv"]    = (void *)GL_PointParameterxv;
    hookMap["glPointSize"]           = (void *)GL_PointSize;
    hookMap["glPointSizex"]          = (void *)GL_PointSizex;
    hookMap["glPolygonOffsetx"]      = (void *)GL_PolygonOffsetx;
    hookMap["glPopMatrix"]           = (void *)GL_PopMatrix;
    hookMap["glPushMatrix"]          = (void *)GL_PushMatrix;
    hookMap["glRotatef"]             = (void *)GL_Rotatef;
    hookMap["glRotatex"]             = (void *)GL_Rotatex;
    hookMap["glSampleCoveragex"]     = (void *)GL_SampleCoveragex;
    hookMap["glScalef"]              = (void *)GL_Scalef;
    hookMap["glScalex"]              = (void *)GL_Scalex;
    hookMap["glShadeModel"]          = (void *)GL_ShadeModel;
    hookMap["glTexCoordPointer"]     = (void *)GL_TexCoordPointer;
    hookMap["glTexEnvf"]             = (void *)GL_TexEnvf;
    hookMap["glTexEnvfv"]            = (void *)GL_TexEnvfv;
    hookMap["glTexEnvi"]             = (void *)GL_TexEnvi;
    hookMap["glTexEnviv"]            = (void *)GL_TexEnviv;
    hookMap["glTexEnvx"]             = (void *)GL_TexEnvx;
    hookMap["glTexEnvxv"]            = (void *)GL_TexEnvxv;
    hookMap["glTexParameterx"]       = (void *)GL_TexParameterx;
    hookMap["glTexParameterxv"]      = (void *)GL_TexParameterxv;
    hookMap["glTranslatef"]          = (void *)GL_Translatef;
    hookMap["glTranslatex"]          = (void *)GL_Translatex;
    hookMap["glVertexPointer"]       = (void *)GL_VertexPointer;
}

}  // namespace agi_layer
